version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: localhost
    environment:
      MYSQL_DATABASE: 'student'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '961149'
      MYSQL_ROOT_PASSWORD: '961149'